# Generated by Django 5.0.1 on 2026-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='user',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tipe',
            field=models.CharField(choices=[('tugas', 'Tugas'), ('belajar', 'Kegiatan Belajar')], default='tugas', max_length=20),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='kegiatan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='waktu_mulai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='waktu_selesai',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
