# Generated by Django 5.0.1 on 2026-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_jadwal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='jam_deadline',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
