# Generated by Django 5.0.1 on 2026-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='is_selesai',
            field=models.BooleanField(default=False),
        ),
    ]
