# Generated by Django 5.0.1 on 2026-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_folder_modul'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='semester',
            field=models.CharField(default='Semester 3', max_length=20),
        ),
    ]
