# Generated by Django 5.0.1 on 2026-06-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_folder_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='semester',
        ),
    ]
