# Generated by Django 5.0.14 on 2026-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_remove_folder_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
                ('jawaban', models.TextField()),
                ('jumlah_digunakan', models.IntegerField(default=0)),
            ],
        ),
    ]
